-- ============================================================================
-- Current diagram and canvas-state storage for the AI Draw.io agent.
--
-- Phase 1 stores the latest canvas XML for a user's diagram. Later phases can
-- add version snapshots, conversations, messages, and tool-event audit tables.
--
-- Run once against the target database after docs/sql/skill.sql.
-- ============================================================================

CREATE DATABASE IF NOT EXISTS ai_draw_io
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ai_draw_io;

CREATE TABLE IF NOT EXISTS diagram (
    id              VARCHAR(64)  NOT NULL COMMENT 'Diagram id generated by the application/client',
    user_id         VARCHAR(64)  NOT NULL COMMENT 'Owner user id',
    title           VARCHAR(255) NOT NULL DEFAULT 'Untitled Diagram' COMMENT 'Display title for the future diagram list',
    diagram_type    VARCHAR(64)  NOT NULL DEFAULT 'basic' COMMENT 'basic, architecture, uml_class, flowchart, etc.',
    thumbnail_url   MEDIUMTEXT            COMMENT 'Homepage thumbnail data URL',
    deleted         TINYINT(1)   NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (id),
    KEY idx_user_updated (user_id, updated_at),
    KEY idx_user_deleted_updated (user_id, deleted, updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'User diagrams';

-- Existing databases created before diagram.current_version was removed should run:
-- docs/sql/migrations/2026-07-02-drop-diagram-current-version.sql
-- ALTER TABLE diagram DROP COLUMN current_version;

CREATE TABLE IF NOT EXISTS diagram_canvas_state (
    diagram_id    VARCHAR(64) NOT NULL COMMENT 'Diagram id',
    user_id       VARCHAR(64) NOT NULL COMMENT 'Owner user id',
    current_xml   LONGTEXT    NOT NULL COMMENT 'Latest complete Draw.io mxGraphModel XML',
    content_hash  VARCHAR(80)          DEFAULT NULL COMMENT 'Canonical SHA-256 hash of latest canvas XML',
    summary       TEXT                 COMMENT 'Compact canvas summary for prompt context',
    analysis_json MEDIUMTEXT           COMMENT 'Latest deterministic analysis JSON',
    version       BIGINT      NOT NULL DEFAULT 1 COMMENT 'Latest canvas version',
    created_at    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    updated_at    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (diagram_id),
    KEY idx_user_updated (user_id, updated_at),
    CONSTRAINT fk_canvas_state_diagram
        FOREIGN KEY (diagram_id) REFERENCES diagram (id)
        ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Latest Draw.io canvas state';

CREATE TABLE IF NOT EXISTS diagram_conversation_message (
    id                BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Message row id',
    diagram_id        VARCHAR(64)  NOT NULL COMMENT 'Diagram id',
    user_id           VARCHAR(64)  NOT NULL COMMENT 'Owner user id',
    session_id        VARCHAR(128)          DEFAULT NULL COMMENT 'Backend or local session id',
    client_message_id VARCHAR(128) NOT NULL COMMENT 'Frontend stable message id for idempotent saves',
    role              VARCHAR(32)  NOT NULL COMMENT 'user or agent',
    content           LONGTEXT     NOT NULL COMMENT 'Conversation message content',
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    updated_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_diagram_user_client_message (diagram_id, user_id, client_message_id),
    KEY idx_diagram_user_created (diagram_id, user_id, created_at),
    KEY idx_user_updated (user_id, updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Diagram conversation messages';
