package org.zipp.ai.application.turn.demand;

public enum DemandResolutionCode {
    CURRENT_INSTRUCTION_EVIDENCE_VERIFIED,
    PLAIN_ONLY_ACTION,
    ATTACHMENT_BINDING_VERIFIED,
    REQUIRED_PROPOSAL_ACCEPTED,
    OPTIONAL_DISCOVERY_ACCEPTED,
    NO_PROJECT_SOURCE_SCOPE,
    OPTIONAL_FALLBACK_SIGNED,
    CLARIFICATION_REQUIRED,
    PROPOSAL_LACKS_CURRENT_INSTRUCTION_EVIDENCE,
    ATTACHMENT_NOT_BOUND_TO_MESSAGE,
    LOW_CONFIDENCE,
    SOURCE_DEMAND_INTERPRETER_UNAVAILABLE
}
