package org.zipp.ai.domain.ingestion.model.valobj;

public enum UploadErrorCode {
    UPLOAD_DISABLED,
    UNSUPPORTED_MEDIA_TYPE,
    DECLARED_SIZE_LIMIT,
    BATCH_FILE_LIMIT,
    UPLOAD_SCOPE_FORBIDDEN,
    ANONYMOUS_SCOPE_FORBIDDEN,
    WORKSPACE_FILE_LIMIT,
    PROCESSING_CONCURRENCY_LIMIT,
    WORKSPACE_RATE_LIMIT,
    IP_RATE_LIMIT,
    ACCOUNT_STORAGE_LIMIT,
    CAPACITY_EXHAUSTED,
    ANONYMOUS_RELEASE_NOT_APPROVED,
    UPLOAD_NOT_FOUND,
    UPLOAD_POLICY_EXPIRED,
    UPLOAD_OBJECT_MISSING,
    UPLOAD_OBJECT_SIZE_MISMATCH,
    UPLOAD_ALREADY_TERMINAL,
    REJECTED_SECURITY,
    REJECTED_LIMIT,
    REJECTED_FORMAT,
    TRANSIENT_DEPENDENCY,
    STALE_FENCE
}
