package org.zipp.ai.domain.material.model.valobj;

public enum CatalogErrorCode {
    REGISTERED_USER_REQUIRED,
    MATERIAL_NOT_FOUND,
    MATERIAL_NOT_ACTIVE,
    MATERIAL_PROMOTION_REQUIRED,
    SCOPE_TARGET_NOT_FOUND,
    LAST_RETAINED_SCOPE,
    CHARTBOOK_NOT_FOUND,
    CHARTBOOK_ARCHIVED,
    DIAGRAM_NOT_FOUND,
    CATALOG_CONFLICT
}
