package org.zipp.ai.domain.material.model.valobj;

public enum CatalogErrorCode {
    REGISTERED_USER_REQUIRED,
    MATERIAL_NOT_FOUND,
    MATERIAL_NOT_ACTIVE,
    MATERIAL_EXPIRED,
    TEMPORARY_MATERIAL_REQUIRED,
    RESTORE_TARGET_UNAVAILABLE,
    READ_LEASE_DENIED,
    DELETION_CONFIRMATION_INVALID,
    MATERIAL_PROMOTION_REQUIRED,
    VERSION_NOT_FOUND,
    REVISION_NOT_FOUND,
    PAGE_NOT_FOUND,
    PREVIEW_UNAVAILABLE,
    REPROCESS_NOT_READY,
    REPROCESS_IN_PROGRESS,
    SCOPE_TARGET_NOT_FOUND,
    LAST_RETAINED_SCOPE,
    CHARTBOOK_NOT_FOUND,
    CHARTBOOK_ARCHIVED,
    DIAGRAM_NOT_FOUND,
    CATALOG_CONFLICT
}
